### ISSUE TITLE
Can't complete RFP Weapons Testing after Wanderer Outfits event

### ISSUE THREAD

**Issue by xathien** [LocalGod79/UrsaPolaris#13]
If the "UPS Wanderer Outfits" event has been completed, the "UPSRnD" mission spawns `ship "Corvette (RFP)" "Jaakaru"` in Wei. Disabling the Jaakaru in Ildaria works fine, but when I get two jumps away, the Jaakaru has recovered some hull--inconveniently the same number of jumps to reach Wei from Ildaria.

**Comment by LocalGod79** [comment]
wow...thanks!

i suspect that the two NPCs having exactly the same name is causing the issue - a fix is committed...
