### ISSUE TITLE
Is the Polar Core supposed to do hull damage or give strength?

### ISSUE THREAD

**Issue by Alkallid** [LocalGod79/UrsaPolaris#2]

**Comment by Alkallid** [comment]
I might use this as a hub because this place is dead.

In OS1, you forgot the ending comma for one of James' sentences.

**Comment by Alkallid** [comment]
In OS2, comma before <first> when he spots you.

**Comment by Alkallid** [comment]
Also, 'spot' and 'he' are overused, you can just cut out "_he_ drags you..."

**Comment by Alkallid** [comment]
OS3: os3b: Ships shan't have an apostrophe.

**Comment by Alkallid** [comment]
I meant "it's scope..." Sorry, can't edit my comments right now.

**Comment by Alkallid** [comment]
Comma should be before so in the line where he roasts your New Greenland ass. (Although incorrectly)

**Comment by Alkallid** [comment]
"Well, we're starting to assemble a team of mostly engineers, and my favour-owing engineer cousin friends here have managed to convince six fellow Syndicate employees to end their contracts as well, and are all joining our organization."
You really want to restructure this run-on.

**Comment by LocalGod79** [comment]
wow - thanks - i'll get on these soon, i promise.

yes, the Polar Core is supposed to do hull damage (which happened only when the shields were down in 0.8.x, but will now also happen when suffering "disruption damage" - it's a balance point to all the goodies that it imparts in an otherwise broken package)

**Comment by Alkallid** [comment]
I'll probably search more later, right n ow I'm scanning Enigma Corp.

**Comment by LocalGod79** [comment]
i'm not averse to pull requests...

**Comment by Alkallid** [comment]
I'm not willing enough to bother...
Yet

**Comment by Alkallid** [comment]
OS4 "You greet him, he stands up..." Either make that a semicolon or add an 'and.'

**Comment by Alkallid** [comment]
"A top tier outfitters..." 
"Well, we have a crack group of engineers already working aboard Honest Abe. I helped them remove all the fancy stuff that I'd been collecting back in the day. Mostly stuff that was mothballed because the business folk didn't want invest in making them more viable, but there was some other stuff in there, too. It's all aboard Honest Abe now, either being reverse engineered, improved, or loaded up for use. The Marius was a sweet ship, though…To her!" 
Wait, did he help strip the Marius or the Abe? Clarify a bit
Space before the toast
Fidn't want _to_ invest

You meet his toast. "Honest Abe is a good ship, and better serves our purposes…" he continues "which I imagine you're beginning to question, since we've talked about opening a top-tier outfitters, and spent a fair bit apparently recruiting weapons engineers. That's only partly true; we've simultaneously recruited the talent required to assemble an asteroid outpost."`     

Comma after "he continues..."

**Comment by Alkallid** [comment]
Just say 'We'll set her up near Hope's equator to serve as both our R&D and project management center.'

**Comment by Alkallid** [comment]
Good choice would be better than thinking; you didn't really have an idea.

I'm also not sure, but shouldn't it be hundreds of millions_'_ worth...?

**Comment by Alkallid** [comment]
OS5 desc.-
Rendevous is one word, and you forgot the period.

**Comment by Alkallid** [comment]
Impossibly wide, improbably honestly sounds stupid
Just say the data is being analyzed the second mention
And just say jump through the systems for a scan

**Comment by Alkallid** [comment]
Okay... so how do I pull request? I can't seem to find a guide, and it would be much less time-cosnuming...

**Comment by Alkallid** [comment]
Okay, I think I figured it out, I can do these myself.

**Comment by Alkallid** [comment]
Okay, I think I figured it out, I can do these myself.

**Comment by Alkallid** [comment]
Okay, I think I figured it out, I can do these myself.

**Comment by Alkallid** [comment]
Okay, I think I figured it out, I can do these myself.

**Comment by Alkallid** [comment]
Okay, I think I figured it out, I can do these myself.

**Comment by Alkallid** [comment]
Okay, I think I figured it out, I can do these myself.

**Comment by Alkallid** [comment]
Are descriptions supposed to not be sentences?

**Comment by Alkallid** [comment]
It's done. https://github.com/Alkallid/UrsaPolaris/blob/master/data/UPMissions.txt
If you could explain how to PR, that'd be great. I only "forked," and don't know how to give it to you.

**Comment by Alkallid** [comment]
I will be back in 18 hours or so.

**Comment by LocalGod79** [comment]
it's late - i'll edit this post in the morning with some instructions.  if you get this before then, are you using the github desktop application?

**Comment by Alkallid** [comment]
Nope, browser. I could've gotten it, though, I think.

**Comment by LocalGod79** [comment]
so, if you get the desktop client, it's super easy.

the client clones the repository locally.  you create a branch, switch to your operating system's file management, and replace the "UPMissions.txt" file with the one you've corrected.  submit pull request.

from the browser (on your fork page) there should be a link at the right side: "Pull request", at the top of the file list (under the code tab), next to "Compare"

**Comment by Alkallid** [comment]
When I go to pull request, it says to compare branches; I type mine in?

**Comment by LocalGod79** [comment]
i'm not sure which button you pressed - white or green?

edit; from _your_ fork page, it should automatically make the comparison, and "Files Changed" will not be 0...

**Comment by Alkallid** [comment]
I think I got it. However, since my computer is sort of broken, I have to use the browser base, so it'll be more complicated, I guess. I understand this though.

**Comment by LocalGod79** [comment]
i think, after merging your p.r., all of these are addressed.
