### ISSUE TITLE
about.txt is the same as license.txt

### ISSUE THREAD

**Issue by dufferzafar** [LocalGod79/UrsaPolaris#7]
The repo is also missing a Readme.md

If you'd like I can open a pull with a Readme that takes data from the [steam page](http://steamcommunity.com/sharedfiles/filedetails/?id=631160921)?

**Comment by puddlejumper9** [comment]
fixed https://github.com/LocalGod79/UrsaPolaris/pull/9

**Comment by LocalGod79** [comment]
merged
